/**
 * CHANNEL REGISTRY — where a published article should actually go, and what each
 * destination expects.
 *
 * The engine already had three channels (LinkedIn, an X thread, a newsletter
 * blurb) generated by one LLM call. That is a fraction of the places a piece can
 * legitimately land, and the LLM was doing work that does not need a model: the
 * per-article social copy in `content-studio/<slug>/social.json` is already
 * written, humanised, and fact-checked by the same gates as the article.
 *
 * So this module is deterministic on purpose. Every channel asset is assembled
 * from material that already passed review: the article's title, its short
 * version, its own social.json, and its real published URL. No new claims can
 * appear at distribution time, which is exactly the property you want when the
 * copy is going out under the brand's name.
 *
 * Each channel carries its own rules because the rules are the whole game. A
 * link that is welcome on LinkedIn gets you banned on Reddit; a cross-post
 * without a canonical tag competes with the original in search. Those are
 * encoded as data, not left to whoever is posting that day.
 */

export type ChannelKind = "social" | "community" | "syndication" | "email" | "video";

/** How a destination treats a self-promotional link. Drives what we generate. */
export type SelfPromoPolicy =
  | "welcome" // our own account, our own audience
  | "contextual" // fine when it answers the actual question
  | "restricted" // only with a disclosure, and only if genuinely on topic
  | "forbidden"; // never lead with a link here

export type ChannelSpec = {
  id: string;
  label: string;
  kind: ChannelKind;
  /** Hard character budget for the body, where the platform has one. */
  maxChars?: number;
  /** Does a bare link belong in the post itself? */
  allowsLinks: boolean;
  selfPromo: SelfPromoPolicy;
  /**
   * True when publishing the full article text there would compete with the
   * original in search. Those channels REQUIRE a canonical URL back to us.
   */
  requiresCanonical?: boolean;
  /** Practical guidance shown in the dashboard next to the draft. */
  note: string;
};

/**
 * The channel set. Ordered roughly by how much of the work is already done for
 * us: owned audiences first, then communities, then syndication.
 */
export const CHANNELS: ChannelSpec[] = [
  {
    id: "linkedin",
    label: "LinkedIn",
    kind: "social",
    maxChars: 3000,
    allowsLinks: true,
    selfPromo: "welcome",
    note: "Best-performing owned channel for B2B infra. Lead with the insight; the link can sit at the end or in the first comment.",
  },
  {
    id: "x_thread",
    label: "X thread",
    kind: "social",
    maxChars: 280,
    allowsLinks: true,
    selfPromo: "welcome",
    note: "One idea per tweet. First tweet carries no link so it is not throttled; the last one has the URL.",
  },
  {
    id: "newsletter",
    label: "Newsletter",
    kind: "email",
    allowsLinks: true,
    selfPromo: "welcome",
    note: "Your own list is the only channel no algorithm sits in front of. Short blurb, one link, no digest padding.",
  },
  {
    id: "facebook",
    label: "Facebook page",
    kind: "social",
    maxChars: 2000,
    allowsLinks: true,
    selfPromo: "welcome",
    note: "Lower priority for developer topics, real for WordPress and regional audiences.",
  },
  {
    id: "instagram",
    label: "Instagram caption",
    kind: "social",
    maxChars: 2200,
    allowsLinks: false,
    selfPromo: "welcome",
    note: "No clickable links in captions, so point to the bio. Pairs with the 1080 card social-studio already renders.",
  },
  {
    id: "youtube_description",
    label: "YouTube description",
    kind: "video",
    maxChars: 5000,
    allowsLinks: true,
    selfPromo: "welcome",
    note: "For the matching video-studio episode. First two lines are what people actually see.",
  },
  {
    id: "reddit",
    label: "Reddit",
    kind: "community",
    maxChars: 10000,
    allowsLinks: true,
    selfPromo: "restricted",
    note: "Answer the question in the comment itself. Link only if it adds something the answer cannot, and disclose that it is ours.",
  },
  {
    id: "hacker_news",
    label: "Hacker News",
    kind: "community",
    allowsLinks: true,
    selfPromo: "contextual",
    note: "Only submit pieces with a genuine technical finding. Marketing framing gets flagged within minutes.",
  },
  {
    id: "dev_to",
    label: "DEV.to",
    kind: "syndication",
    allowsLinks: true,
    selfPromo: "welcome",
    requiresCanonical: true,
    note: "Set canonical_url to our URL or the copy competes with the original.",
  },
  {
    id: "hashnode",
    label: "Hashnode",
    kind: "syndication",
    allowsLinks: true,
    selfPromo: "welcome",
    requiresCanonical: true,
    note: "Same canonical rule as DEV. Good reach for deploy and database topics.",
  },
  {
    id: "medium",
    label: "Medium",
    kind: "syndication",
    allowsLinks: true,
    selfPromo: "welcome",
    requiresCanonical: true,
    note: "Import via Medium's own tool so the canonical is set for you.",
  },
  {
    id: "community_chat",
    label: "Discord / Slack communities",
    kind: "community",
    maxChars: 1200,
    allowsLinks: true,
    selfPromo: "contextual",
    note: "Share in the channel the topic belongs to, with one sentence on why it is useful. Never paste the same message into ten servers.",
  },
];

export const CHANNEL_IDS = CHANNELS.map((c) => c.id);
export function getChannel(id: string): ChannelSpec | undefined {
  return CHANNELS.find((c) => c.id === id);
}

/* -------------------------------------------------------------------------- *
 * Source material
 * -------------------------------------------------------------------------- */

/** Everything a channel builder is allowed to draw from. All pre-reviewed. */
export type ArticleSource = {
  slug: string;
  title: string;
  url: string;
  /** The article's own short-version box or meta description. */
  summary: string;
  /** Sentences from the short version, used to build threads and bullets. */
  points: string[];
  tags: string[];
  /** Reused verbatim when present: already written and already checked. */
  social?: {
    x?: string;
    linkedin?: string;
    thread?: string[];
  } | null;
};

export type ChannelAsset = {
  channel: string;
  /** What a human copies out. */
  body: string;
  /** Set for channels that have one (newsletter subject, HN title). */
  subject?: string;
  /** Threads keep their parts separate so each can be posted in order. */
  parts?: string[];
  hashtags?: string[];
  canonicalUrl?: string;
  /** Rules the poster needs to see at the moment of posting. */
  guidance: string;
};

const clip = (s: string, n: number): string => {
  const t = s.replace(/\s+/g, " ").trim();
  if (t.length <= n) return t;
  return `${t.slice(0, n - 1).replace(/\s+\S*$/, "")}\u2026`;
};

const sentences = (s: string): string[] =>
  (s || "")
    .split(/(?<=[.!?])\s+/)
    .map((x) => x.trim())
    .filter(Boolean);

const tagLine = (tags: string[], max = 5): string =>
  tags
    .slice(0, max)
    .map((t) => (t.startsWith("#") ? t : `#${t}`))
    .join(" ");

/* -------------------------------------------------------------------------- *
 * Builders. One per channel, deterministic, no model call.
 * -------------------------------------------------------------------------- */

function buildLinkedIn(a: ArticleSource): ChannelAsset {
  const body =
    a.social?.linkedin?.trim() ||
    [
      a.title,
      "",
      clip(a.points.slice(0, 3).join(" ") || a.summary, 700),
      "",
      `Full guide: ${a.url}`,
      "",
      tagLine(a.tags),
    ].join("\n");
  return {
    channel: "linkedin",
    body: clip(body, 3000),
    hashtags: a.tags.slice(0, 5),
    guidance: getChannel("linkedin")!.note,
  };
}

function buildXThread(a: ArticleSource): ChannelAsset {
  const parts =
    a.social?.thread?.length
      ? a.social.thread
      : [
          clip(a.title, 260),
          ...a.points.slice(0, 4).map((p) => clip(p, 260)),
          clip(`Full walkthrough:\n${a.url}\n${tagLine(a.tags, 3)}`, 260),
        ];
  return {
    channel: "x_thread",
    body: parts.join("\n\n---\n\n"),
    parts,
    guidance: getChannel("x_thread")!.note,
  };
}

function buildNewsletter(a: ArticleSource): ChannelAsset {
  const lead = a.points[0] ?? a.summary;
  return {
    channel: "newsletter",
    subject: clip(a.title, 78),
    body: [
      clip(lead, 240),
      "",
      clip(a.points.slice(1, 3).join(" ") || a.summary, 420),
      "",
      `Read it here: ${a.url}`,
    ].join("\n"),
    guidance: getChannel("newsletter")!.note,
  };
}

function buildFacebook(a: ArticleSource): ChannelAsset {
  return {
    channel: "facebook",
    body: clip([a.title, "", clip(a.summary, 500), "", a.url].join("\n"), 2000),
    guidance: getChannel("facebook")!.note,
  };
}

function buildInstagram(a: ArticleSource): ChannelAsset {
  return {
    channel: "instagram",
    body: clip(
      [
        a.title,
        "",
        clip(a.points.slice(0, 2).join(" ") || a.summary, 600),
        "",
        "Full guide linked in bio.",
        "",
        tagLine(a.tags, 8),
      ].join("\n"),
      2200,
    ),
    hashtags: a.tags.slice(0, 8),
    guidance: getChannel("instagram")!.note,
  };
}

function buildYouTubeDescription(a: ArticleSource): ChannelAsset {
  return {
    channel: "youtube_description",
    body: [
      clip(a.summary, 300),
      "",
      `Written version: ${a.url}`,
      "",
      "In this video:",
      ...a.points.slice(0, 5).map((p) => `- ${clip(p, 110)}`),
      "",
      tagLine(a.tags, 5),
    ].join("\n"),
    guidance: getChannel("youtube_description")!.note,
  };
}

function buildReddit(a: ArticleSource): ChannelAsset {
  // Deliberately shaped as an answer, not a promo. The link is optional and
  // disclosed, because that is the only version of this that is welcome.
  return {
    channel: "reddit",
    body: [
      clip(a.points.slice(0, 3).join(" ") || a.summary, 900),
      "",
      "The short version of what usually fixes it:",
      ...a.points.slice(0, 4).map((p) => `- ${clip(p, 160)}`),
      "",
      `(I work at Kloudbean and we wrote this up in more depth here: ${a.url} — happy to answer follow-ups in the thread either way.)`,
    ].join("\n"),
    guidance: getChannel("reddit")!.note,
  };
}

function buildHackerNews(a: ArticleSource): ChannelAsset {
  return {
    channel: "hacker_news",
    subject: clip(a.title.replace(/^(how to|why)\s+/i, (m) => m), 80),
    body: [
      `Submission URL: ${a.url}`,
      "",
      "If you comment, lead with the technical finding, not the product:",
      ...a.points.slice(0, 3).map((p) => `- ${clip(p, 160)}`),
    ].join("\n"),
    guidance: getChannel("hacker_news")!.note,
  };
}

function buildSyndication(a: ArticleSource, channel: string): ChannelAsset {
  return {
    channel,
    subject: a.title,
    body: [
      `Cross-post the full article, then set the canonical URL to:`,
      a.url,
      "",
      "Suggested intro paragraph:",
      clip(a.summary, 400),
      "",
      `Tags: ${a.tags.map((t) => t.replace(/^#/, "")).slice(0, 4).join(", ")}`,
    ].join("\n"),
    canonicalUrl: a.url,
    guidance: getChannel(channel)!.note,
  };
}

function buildCommunityChat(a: ArticleSource): ChannelAsset {
  return {
    channel: "community_chat",
    body: clip(
      [`${clip(a.points[0] ?? a.summary, 300)}`, "", `Wrote it up here: ${a.url}`].join("\n"),
      1200,
    ),
    guidance: getChannel("community_chat")!.note,
  };
}

/** Build the asset for one channel. Returns null for an unknown channel id. */
export function buildChannelAsset(channel: string, a: ArticleSource): ChannelAsset | null {
  switch (channel) {
    case "linkedin":
      return buildLinkedIn(a);
    case "x_thread":
      return buildXThread(a);
    case "newsletter":
      return buildNewsletter(a);
    case "facebook":
      return buildFacebook(a);
    case "instagram":
      return buildInstagram(a);
    case "youtube_description":
      return buildYouTubeDescription(a);
    case "reddit":
      return buildReddit(a);
    case "hacker_news":
      return buildHackerNews(a);
    case "dev_to":
    case "hashnode":
    case "medium":
      return buildSyndication(a, channel);
    case "community_chat":
      return buildCommunityChat(a);
    default:
      return null;
  }
}

/** Build every channel asset for an article. */
export function buildAllChannelAssets(a: ArticleSource, only?: string[]): ChannelAsset[] {
  const ids = only?.length ? only : CHANNEL_IDS;
  return ids
    .map((id) => buildChannelAsset(id, a))
    .filter((x): x is ChannelAsset => x !== null);
}

/** Split a summary into the point list the builders use. */
export function pointsFromSummary(summary: string, fallback: string[] = []): string[] {
  const s = sentences(summary);
  return s.length ? s : fallback;
}
