import "@tanstack/react-start/server-only";
import fs from "node:fs";
import path from "node:path";

/**
 * Publish-state reconciliation — WordPress is the single source of truth.
 *
 * THE PROBLEM THIS FIXES
 * Three places record whether an article is published: the live WordPress site,
 * the engine's database, and the committed content-studio/_published.json
 * manifest. They drifted badly in practice: the manifest was regenerated by a
 * manual script, nobody re-ran it, and the engine reported 21 published articles
 * when 38 were actually live. Every downstream decision (internal linking,
 * publish planning, reporting) was then made on stale data.
 *
 * THE FIX
 * Fetch what is live from WordPress, match it to articles on disk, and correct
 * the database in BOTH directions:
 *   - live on WordPress but not marked published  -> promote (with the real date/URL)
 *   - marked published but no longer live         -> demote back to review
 * Then rewrite the manifest so the committed record stays accurate too.
 *
 * applyPublishedManifest() in ingest-content-studio.ts deliberately only ever
 * promotes, because it runs on boot from a possibly-old file and must not
 * un-publish things. This module is the opposite: it talks to WordPress
 * directly, so it is allowed to correct state downward as well.
 */

export type LivePost = {
  id: number;
  slug: string;
  link: string;
  dateGmt: string;
  title: string;
};

export type MatchedArticle = {
  slug: string;
  wpSlug: string;
  wpPostId: number;
  publishedUrl: string;
  publishedAt: string;
  matchedBy: "verified" | "slug" | "title" | "slug-prefix";
};

export type ReconcileReport = {
  ok: boolean;
  livePosts: number;
  articlesOnDisk: number;
  matched: number;
  /** Live on WordPress, and the DB now agrees. */
  promoted: string[];
  /** DB said published, WordPress says otherwise. Corrected downward. */
  demoted: string[];
  /** Already correct, no change needed. */
  unchanged: number;
  /** Live WP posts with no content-studio counterpart (legacy blog content). */
  unmatchedLive: number;
  manifestWritten: boolean;
  error?: string;
};

/**
 * Live WP slugs whose names bear no reliable relation to the folder slug.
 * Verified by reading both titles side by side. Kept in sync with
 * scripts/sync-published-from-wordpress.mjs.
 */
const OVERRIDES: Record<string, string> = {
  "server-backups-that-actually-restore-a-practical-guide": "server-backups-guide",
  "ksa-wordpress-hosting": "arabic-wordpress-hosting",
  "how-to-add-a-managed-database-postgresql-or-mysql-to-your-app":
    "add-managed-database-to-your-app",
  "the-ai-built-app-security-checklist-secure-your-vibe-coded-app":
    "ai-built-app-security-checklist",
};

const ENGINE_SOURCE = "content-studio";

function decodeEntities(s: string): string {
  return (s || "")
    .replace(/&#8217;|&#039;|&apos;|&#8216;/g, "'")
    .replace(/&#8220;|&#8221;|&quot;/g, '"')
    .replace(/&amp;/g, "&")
    .replace(/&#8211;|&#8212;/g, "-")
    .replace(/&nbsp;/g, " ");
}

function norm(s: string): string {
  return decodeEntities(s).toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

export function hasWordPressConfigured(): boolean {
  return Boolean(
    process.env.WP_SITE_URL && process.env.WP_USERNAME && process.env.WP_APP_PASSWORD,
  );
}

/** Every published post on the site, paged through the WP REST API. */
export async function fetchLivePosts(): Promise<LivePost[]> {
  const site = (process.env.WP_SITE_URL ?? "").replace(/\/+$/, "");
  const auth =
    "Basic " +
    Buffer.from(`${process.env.WP_USERNAME}:${process.env.WP_APP_PASSWORD}`).toString("base64");

  const out: LivePost[] = [];
  for (let page = 1; page <= 30; page++) {
    const ctl = new AbortController();
    const timer = setTimeout(() => ctl.abort(), 30_000);
    let res: Response;
    try {
      res = await fetch(
        `${site}/wp-json/wp/v2/posts?status=publish&per_page=100&page=${page}` +
          `&_fields=id,slug,link,date_gmt,title`,
        { headers: { Authorization: auth }, signal: ctl.signal },
      );
    } finally {
      clearTimeout(timer);
    }
    if (res.status === 400) break; // past the last page
    if (!res.ok) throw new Error(`WordPress responded ${res.status} ${res.statusText}`);
    const batch = (await res.json()) as {
      id: number;
      slug: string;
      link: string;
      date_gmt: string;
      title: { rendered: string };
    }[];
    if (!batch.length) break;
    for (const p of batch) {
      out.push({
        id: p.id,
        slug: p.slug,
        link: p.link,
        dateGmt: p.date_gmt,
        title: p.title?.rendered ?? "",
      });
    }
    if (page >= Number(res.headers.get("x-wp-totalpages") ?? "1")) break;
  }
  return out;
}

type DiskArticle = { slug: string; title: string; metaTitle: string };

/** Articles that exist as content-studio/<slug>/<slug>.html. */
export function listDiskArticles(root?: string): DiskArticle[] {
  const dir = root ?? path.join(process.cwd(), "content-studio");
  if (!fs.existsSync(dir)) return [];
  const out: DiskArticle[] = [];
  for (const name of fs.readdirSync(dir)) {
    if (name.startsWith("_") || name.startsWith(".") || name === "assets" || name === "images") {
      continue;
    }
    const file = path.join(dir, name, `${name}.html`);
    if (!fs.existsSync(file)) continue;
    const html = fs.readFileSync(file, "utf8");
    const rawTitle = (html.match(/<title>([\s\S]*?)<\/title>/i)?.[1] || "").trim();
    const h1 = (html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1] || "")
      .replace(/<[^>]+>/g, "")
      .trim();
    const metaTitle = rawTitle || h1;
    const title = (rawTitle || h1).replace(/\s*[—|]\s*Kloudbean.*$/i, "").trim();
    out.push({ slug: name, title, metaTitle });
  }
  return out;
}

/**
 * Match live WordPress posts to content-studio articles.
 * Order matters: the most reliable signal wins, and each post/article is only
 * claimed once, so a weaker rule can never steal an already-matched pair.
 */
export function matchLiveToDisk(posts: LivePost[], disk: DiskArticle[]): MatchedArticle[] {
  const bySlug = new Map(disk.map((d) => [d.slug, d]));
  const usedPosts = new Set<number>();
  const claimedSlugs = new Set<string>();
  const matched: MatchedArticle[] = [];

  const take = (post: LivePost, slug: string, how: MatchedArticle["matchedBy"]) => {
    if (!slug || usedPosts.has(post.id) || claimedSlugs.has(slug)) return;
    usedPosts.add(post.id);
    claimedSlugs.add(slug);
    const d = new Date(post.dateGmt.endsWith("Z") ? post.dateGmt : `${post.dateGmt}Z`);
    matched.push({
      slug,
      wpSlug: post.slug,
      wpPostId: post.id,
      publishedUrl: post.link,
      publishedAt: (Number.isNaN(d.getTime()) ? new Date() : d).toISOString(),
      matchedBy: how,
    });
  };

  // 1. hand-verified overrides
  for (const [wpSlug, folder] of Object.entries(OVERRIDES)) {
    const p = posts.find((x) => x.slug === wpSlug);
    if (p && bySlug.has(folder)) take(p, folder, "verified");
  }
  // 2. identical slug
  for (const p of posts) if (bySlug.has(p.slug)) take(p, p.slug, "slug");
  // 3. identical normalised title (visible title or meta title)
  for (const p of posts) {
    const pt = norm(p.title);
    const hit = disk.find((d) => norm(d.title) === pt || norm(d.metaTitle) === pt);
    if (hit) take(p, hit.slug, "title");
  }
  // 4. WP slug is the folder slug plus extra words; longest folder slug wins
  const byLen = [...disk].sort((a, b) => b.slug.length - a.slug.length);
  for (const p of posts) {
    const hit = byLen.find((d) => p.slug === d.slug || p.slug.startsWith(`${d.slug}-`));
    if (hit) take(p, hit.slug, "slug-prefix");
  }

  matched.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt));
  return matched;
}

/** Rewrite content-studio/_published.json so the committed record matches reality. */
export function writeManifest(matched: MatchedArticle[], root?: string): void {
  const dir = root ?? path.join(process.cwd(), "content-studio");
  const out = path.join(dir, "_published.json");
  const body = {
    note:
      "Published articles, reconciled from live WordPress. Committed on purpose: the engine DB " +
      "is ephemeral, so the boot sync re-applies this on every start. Regenerate with: " +
      "node scripts/sync-published-from-wordpress.mjs (or the engine reconciler, which " +
      "refreshes it automatically).",
    generated_at: new Date().toISOString(),
    count: matched.length,
    published: matched.map((m) => ({
      slug: m.slug,
      wp_slug: m.wpSlug,
      wp_post_id: m.wpPostId,
      published_url: m.publishedUrl,
      published_at: m.publishedAt,
      matched_by: m.matchedBy,
    })),
  };
  fs.writeFileSync(out, `${JSON.stringify(body, null, 2)}\n`);
}

/**
 * Reconcile the database against live WordPress, correcting drift in both
 * directions, and refresh the committed manifest.
 *
 * Safe to run repeatedly: it only writes rows whose state is actually wrong.
 * It never touches WordPress, only our own record of it.
 */
export async function reconcilePublishState(
  opts: {
    writeManifestFile?: boolean;
    allowDemote?: boolean;
    root?: string;
    log?: (m: string) => void;
  } = {},
): Promise<ReconcileReport> {
  const log = opts.log ?? (() => {});
  const writeManifestFile = opts.writeManifestFile ?? true;
  const allowDemote = opts.allowDemote ?? true;

  const empty: ReconcileReport = {
    ok: false,
    livePosts: 0,
    articlesOnDisk: 0,
    matched: 0,
    promoted: [],
    demoted: [],
    unchanged: 0,
    unmatchedLive: 0,
    manifestWritten: false,
  };

  if (!hasWordPressConfigured()) {
    return { ...empty, error: "WordPress not configured (WP_SITE_URL/WP_USERNAME/WP_APP_PASSWORD)" };
  }

  let posts: LivePost[];
  try {
    posts = await fetchLivePosts();
  } catch (e) {
    return { ...empty, error: `fetch live posts: ${String((e as Error)?.message ?? e)}` };
  }

  const disk = listDiskArticles(opts.root);
  const matched = matchLiveToDisk(posts, disk);
  const liveBySlug = new Map(matched.map((m) => [m.slug, m]));

  const articlesRepo = await import("@/server/db/repos/articles");
  const rows = await articlesRepo.listArticles({ limit: 5000 });

  const promoted: string[] = [];
  const demoted: string[] = [];
  let unchanged = 0;

  for (const row of rows) {
    if (row.engine_source && row.engine_source !== ENGINE_SOURCE) continue;
    const slug = row.url_slug;
    if (!slug) continue;
    const live = liveBySlug.get(slug);
    const dbSaysPublished = row.status === "published";

    if (live && !dbSaysPublished) {
      const perf = (row.performance_data as Record<string, unknown> | null) ?? {};
      await articlesRepo.updateArticle(row.id, {
        status: "published",
        approval_status: "published",
        published_at: new Date(live.publishedAt),
        published_url: live.publishedUrl,
        // Keep the WordPress post id where the publisher already looks for it,
        // so later link injection can address the post without a fresh lookup.
        performance_data: { ...perf, wp_post_id: live.wpPostId },
      });
      promoted.push(slug);
    } else if (!live && dbSaysPublished && allowDemote) {
      await articlesRepo.updateArticle(row.id, {
        status: "review",
        approval_status: "none",
        published_url: null,
      });
      demoted.push(slug);
    } else if (live && dbSaysPublished) {
      unchanged++;
    }
  }

  let manifestWritten = false;
  if (writeManifestFile) {
    try {
      writeManifest(matched, opts.root);
      manifestWritten = true;
    } catch (e) {
      log(`manifest write failed: ${String((e as Error)?.message ?? e)}`);
    }
  }

  const report: ReconcileReport = {
    ok: true,
    livePosts: posts.length,
    articlesOnDisk: disk.length,
    matched: matched.length,
    promoted,
    demoted,
    unchanged,
    unmatchedLive: posts.length - matched.length,
    manifestWritten,
  };

  log(
    `publish state: ${report.matched}/${report.livePosts} live posts matched, ` +
      `${promoted.length} promoted, ${demoted.length} demoted, ${unchanged} already correct`,
  );
  if (promoted.length) log(`  promoted: ${promoted.join(", ")}`);
  if (demoted.length) log(`  demoted: ${demoted.join(", ")}`);

  return report;
}
