import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { AppLayout } from "@/components/AppLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useState } from "react";
import { Sparkles, Loader2, Plus, Trash2, BookOpen, Lightbulb } from "lucide-react";
import { toast } from "sonner";
import {
  listExperienceSnippetsFn,
  seedExperienceSnippetsFn,
  addExperienceSnippetFn,
  updateExperienceSnippetFn,
  deleteExperienceSnippetFn,
} from "@/lib/experience.functions";

export const Route = createFileRoute("/experience")({ component: ExperiencePage });

const KIND_COLOR: Record<string, string> = {
  lesson: "#4F1AF3",
  mistake: "#f97316",
  migration: "#0ea5e9",
  incident: "#ef4444",
  benchmark: "#22c55e",
};

function ExperiencePage() {
  const qc = useQueryClient();
  const listFn = useServerFn(listExperienceSnippetsFn);
  const seedFn = useServerFn(seedExperienceSnippetsFn);
  const addFn = useServerFn(addExperienceSnippetFn);
  const updateFn = useServerFn(updateExperienceSnippetFn);
  const deleteFn = useServerFn(deleteExperienceSnippetFn);

  const { data, refetch, isLoading } = useQuery({
    queryKey: ["experience-snippets"],
    queryFn: () => listFn({}),
  });

  const [title, setTitle] = useState("");
  const [kind, setKind] = useState("lesson");
  const [body, setBody] = useState("");
  const [tags, setTags] = useState("");

  const seedMut = useMutation({
    mutationFn: () => seedFn({}),
    onSuccess: (r) => {
      toast.success(
        `Added ${r.inserted} starter lessons${r.skipped ? ` (${r.skipped} already existed)` : ""}`,
      );
      refetch();
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const addMut = useMutation({
    mutationFn: () =>
      addFn({
        data: {
          title: title.trim(),
          kind: kind as "lesson" | "mistake" | "migration" | "incident" | "benchmark",
          body: body.trim(),
          tags: tags
            .split(",")
            .map((t) => t.trim().toLowerCase())
            .filter(Boolean),
        },
      }),
    onSuccess: () => {
      toast.success("Lesson added — it will be matched into relevant articles automatically");
      setTitle("");
      setBody("");
      setTags("");
      refetch();
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const toggleActive = useMutation({
    mutationFn: (vars: { id: string; active: boolean }) =>
      updateFn({ data: { id: vars.id, active: vars.active } }),
    onSuccess: () => refetch(),
    onError: (e: Error) => toast.error(e.message),
  });

  const deleteMut = useMutation({
    mutationFn: (id: string) => deleteFn({ data: { id } }),
    onSuccess: () => {
      toast.success("Removed");
      refetch();
      qc.invalidateQueries({ queryKey: ["experience-snippets"] });
    },
    onError: (e: Error) => toast.error(e.message),
  });

  const snippets = data?.snippets ?? [];

  return (
    <AppLayout>
      <div className="mx-auto max-w-4xl px-8 py-8">
        <header className="mb-6">
          <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-border bg-card/60 px-3 py-1 font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
            <BookOpen className="h-3 w-3 text-primary" />
            Experience Engine — E-E-A-T
          </div>
          <h1 className="text-display text-3xl font-semibold tracking-tight">
            Real lessons, not generic AI explanation
          </h1>
          <p className="mt-2 max-w-2xl text-sm text-muted-foreground">
            A curated library of genuine operational lessons — migration gotchas, common mistakes,
            incidents, benchmarks. Every article generated by the engine automatically pulls in 1-2
            lessons that match its topic, so it reads like it was written by someone who's actually
            run the infrastructure, not a rephrased explainer.
          </p>
          {(data?.total ?? 0) === 0 && (
            <Button
              className="mt-4"
              onClick={() => seedMut.mutate()}
              disabled={seedMut.isPending}
              title="Add a starter library of 15 real operational lessons to get started."
              style={{ background: "var(--gradient-brand)", color: "var(--brand-foreground)" }}
            >
              {seedMut.isPending ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Sparkles className="mr-2 h-4 w-4" />
              )}
              Add starter library (15 lessons)
            </Button>
          )}
        </header>

        <section className="mb-8 rounded-xl border border-border bg-card/60 p-5">
          <h2 className="mb-3 flex items-center gap-2 text-sm font-semibold">
            <Plus className="h-4 w-4 text-primary" /> Add a lesson
          </h2>
          <div className="grid gap-3 sm:grid-cols-2">
            <div className="sm:col-span-2">
              <Label className="text-xs">Title</Label>
              <Input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="e.g. Redis eviction policy defaults"
              />
            </div>
            <div>
              <Label className="text-xs">Kind</Label>
              <Select value={kind} onValueChange={setKind}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="lesson">Lesson</SelectItem>
                  <SelectItem value="mistake">Common mistake</SelectItem>
                  <SelectItem value="migration">Migration insight</SelectItem>
                  <SelectItem value="incident">Incident pattern</SelectItem>
                  <SelectItem value="benchmark">Benchmark</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label className="text-xs">
                Tags (comma-separated — matched against article topics)
              </Label>
              <Input
                value={tags}
                onChange={(e) => setTags(e.target.value)}
                placeholder="redis, cache, performance"
              />
            </div>
            <div className="sm:col-span-2">
              <Label className="text-xs">
                The lesson (write as a genuine, honest pattern — no invented customer names or fake
                stats)
              </Label>
              <Textarea
                rows={4}
                value={body}
                onChange={(e) => setBody(e.target.value)}
                placeholder="Describe the real operational pattern, mistake, or insight…"
              />
            </div>
          </div>
          <Button
            className="mt-3"
            size="sm"
            disabled={addMut.isPending || !title.trim() || !body.trim()}
            onClick={() => addMut.mutate()}
            title="Save this lesson so the engine can weave it into matching articles."
          >
            {addMut.isPending ? (
              <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" />
            ) : (
              <Plus className="mr-2 h-3.5 w-3.5" />
            )}
            Add lesson
          </Button>
        </section>

        <section>
          <h2 className="mb-3 flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-muted-foreground">
            <Lightbulb className="h-4 w-4 text-primary" /> Library ({snippets.length})
          </h2>
          {isLoading ? (
            <div className="py-8 text-center text-sm text-muted-foreground">Loading…</div>
          ) : snippets.length === 0 ? (
            <div className="rounded-xl border border-dashed border-border bg-card/30 px-6 py-10 text-center text-sm text-muted-foreground">
              No lessons yet — add the starter library above or write your own.
            </div>
          ) : (
            <div className="space-y-2">
              {snippets.map((s) => (
                <div
                  key={s.id}
                  className={`rounded-lg border border-border bg-card/60 p-4 ${s.active ? "" : "opacity-50"}`}
                >
                  <div className="mb-1.5 flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <span
                        className="rounded-full px-2 py-0.5 text-[10px] font-medium uppercase"
                        style={{
                          background: (KIND_COLOR[s.kind] ?? "#888") + "22",
                          color: KIND_COLOR[s.kind] ?? "#aaa",
                        }}
                      >
                        {s.kind}
                      </span>
                      <span className="text-sm font-medium">{s.title}</span>
                    </div>
                    <div className="flex items-center gap-1.5">
                      <span className="text-[10px] text-muted-foreground">
                        used {s.usage_count}×
                      </span>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => toggleActive.mutate({ id: s.id, active: !s.active })}
                        title={
                          s.active ? "Deactivate (won't be used in new articles)" : "Reactivate"
                        }
                      >
                        {s.active ? "Active" : "Inactive"}
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => deleteMut.mutate(s.id)}
                        title="Delete this lesson permanently."
                      >
                        <Trash2 className="h-3.5 w-3.5 text-destructive" />
                      </Button>
                    </div>
                  </div>
                  <p className="mb-2 text-xs text-muted-foreground">{s.body}</p>
                  <div className="flex flex-wrap gap-1">
                    {s.tags.map((t) => (
                      <span key={t} className="rounded bg-secondary/60 px-1.5 py-0.5 text-[10px]">
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>
      </div>
    </AppLayout>
  );
}
