/** Renders a human-readable production script (Markdown) for one video. */
import { beatMs, videoDurationMs } from "./template.mjs";

function fmt(sec) {
  const s = Math.round(sec);
  const m = Math.floor(s / 60);
  const r = s % 60;
  return `${m}:${String(r).padStart(2, "0")}`;
}

export function buildScriptMarkdown(video, index) {
  const totalSec = videoDurationMs(video) / 1000;
  const lines = [];
  lines.push(`# ${video.title}`);
  lines.push("");
  lines.push(`**Video #${String(index).padStart(2, "0")}** · Kloudbean explainer`);
  lines.push("");
  lines.push(`| | |`);
  lines.push(`|---|---|`);
  lines.push(`| **ICP / audience** | ${video.icpName ?? "General"} |`);
  lines.push(`| **Format** | ${video.format ?? "explainer"} · ${video.aspect ?? "16:9"} |`);
  lines.push(`| **Runtime** | ~${fmt(totalSec)} (${video.beats.length} beats) |`);
  lines.push(`| **Slug** | \`${video.slug}\` |`);
  lines.push("");
  if (video.hook) {
    lines.push(`> **Hook:** ${video.hook}`);
    lines.push("");
  }
  if (video.summary) {
    lines.push(video.summary);
    lines.push("");
  }

  lines.push(`## Beat-by-beat script`);
  lines.push("");
  lines.push(`| # | Time | On-screen | Narration (voiceover) | Scene |`);
  lines.push(`|---|------|-----------|-----------------------|-------|`);
  let acc = 0;
  video.beats.forEach((b, i) => {
    const dur = beatMs(b) / 1000;
    const start = acc;
    acc += dur;
    const clean = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(
      `| ${i + 1} | ${fmt(start)}–${fmt(acc)} | ${clean(b.on_screen)} | ${clean(b.narration)} | ${b.scene ?? "generic"} |`,
    );
  });
  lines.push("");

  // Full voiceover as one block (paste into ElevenLabs, save the audio here).
  lines.push(`## Voiceover`);
  lines.push("");
  lines.push(`Generate this in ElevenLabs, save it as \`voiceover.mp3\` in this folder, then render with \`--voiceover\` (beats auto-sync to the audio). For tighter sync, save per-beat clips as \`vo/1.mp3\`, \`vo/2.mp3\`, …`);
  lines.push("");
  lines.push(video.beats.map((b) => b.narration).join(" "));
  lines.push("");

  if (video.cta) {
    lines.push(`## Call to action`);
    lines.push("");
    lines.push(video.cta);
    lines.push("");
  }

  lines.push(`## Files`);
  lines.push("");
  lines.push(`- \`storyboard.html\` — open in a browser to watch the animated storyboard.`);
  lines.push(`- \`voiceover.mp3\` — (optional) drop your ElevenLabs audio here for \`--voiceover\`.`);
  lines.push(`- \`video.mp4\` / \`video-reel.mp4\` — rendered 16:9 / 9:16 video (run \`npm run render-all\`).`);
  lines.push(`- \`script.md\` — this file.`);
  lines.push("");
  lines.push(`_Generated by Kloudbean Video Studio. Content grounded in Kloudbean's real capabilities; no invented figures._`);
  lines.push("");
  return lines.join("\n");
}
