/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RaffleRouteImport } from './routes/raffle'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as IndexRouteImport } from './routes/index'

const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleRoute = RaffleRouteImport.update({
  id: '/raffle',
  path: '/raffle',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/engine': typeof EngineRoute
  '/keywords': typeof KeywordsRoute
  '/performance': typeof PerformanceRoute
  '/raffle': typeof RaffleRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/engine': typeof EngineRoute
  '/keywords': typeof KeywordsRoute
  '/performance': typeof PerformanceRoute
  '/raffle': typeof RaffleRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/engine': typeof EngineRoute
  '/keywords': typeof KeywordsRoute
  '/performance': typeof PerformanceRoute
  '/raffle': typeof RaffleRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefs'
    | '/calendar'
    | '/engine'
    | '/keywords'
    | '/performance'
    | '/raffle'
    | '/settings'
    | '/strategy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefs'
    | '/calendar'
    | '/engine'
    | '/keywords'
    | '/performance'
    | '/raffle'
    | '/settings'
    | '/strategy'
  id:
    | '__root__'
    | '/'
    | '/briefs'
    | '/calendar'
    | '/engine'
    | '/keywords'
    | '/performance'
    | '/raffle'
    | '/settings'
    | '/strategy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefsRoute: typeof BriefsRoute
  CalendarRoute: typeof CalendarRoute
  EngineRoute: typeof EngineRoute
  KeywordsRoute: typeof KeywordsRoute
  PerformanceRoute: typeof PerformanceRoute
  RaffleRoute: typeof RaffleRoute
  SettingsRoute: typeof SettingsRoute
  StrategyRoute: typeof StrategyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle': {
      id: '/raffle'
      path: '/raffle'
      fullPath: '/raffle'
      preLoaderRoute: typeof RaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefsRoute: BriefsRoute,
  CalendarRoute: CalendarRoute,
  EngineRoute: EngineRoute,
  KeywordsRoute: KeywordsRoute,
  PerformanceRoute: PerformanceRoute,
  RaffleRoute: RaffleRoute,
  SettingsRoute: SettingsRoute,
  StrategyRoute: StrategyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
