/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicalMapRouteImport } from './routes/topical-map'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as RaffleRouteImport } from './routes/raffle'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as IndexRouteImport } from './routes/index'

const TopicalMapRoute = TopicalMapRouteImport.update({
  id: '/topical-map',
  path: '/topical-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleRoute = RaffleRouteImport.update({
  id: '/raffle',
  path: '/raffle',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/engine': typeof EngineRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/keywords': typeof KeywordsRoute
  '/knowledge': typeof KnowledgeRoute
  '/performance': typeof PerformanceRoute
  '/raffle': typeof RaffleRoute
  '/reels': typeof ReelsRoute
  '/scope': typeof ScopeRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/tools': typeof ToolsRoute
  '/topical-map': typeof TopicalMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/engine': typeof EngineRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/keywords': typeof KeywordsRoute
  '/knowledge': typeof KnowledgeRoute
  '/performance': typeof PerformanceRoute
  '/raffle': typeof RaffleRoute
  '/reels': typeof ReelsRoute
  '/scope': typeof ScopeRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/tools': typeof ToolsRoute
  '/topical-map': typeof TopicalMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/engine': typeof EngineRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/keywords': typeof KeywordsRoute
  '/knowledge': typeof KnowledgeRoute
  '/performance': typeof PerformanceRoute
  '/raffle': typeof RaffleRoute
  '/reels': typeof ReelsRoute
  '/scope': typeof ScopeRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/tools': typeof ToolsRoute
  '/topical-map': typeof TopicalMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefs'
    | '/calendar'
    | '/engine'
    | '/help'
    | '/how-it-works'
    | '/keywords'
    | '/knowledge'
    | '/performance'
    | '/raffle'
    | '/reels'
    | '/scope'
    | '/settings'
    | '/strategy'
    | '/tools'
    | '/topical-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefs'
    | '/calendar'
    | '/engine'
    | '/help'
    | '/how-it-works'
    | '/keywords'
    | '/knowledge'
    | '/performance'
    | '/raffle'
    | '/reels'
    | '/scope'
    | '/settings'
    | '/strategy'
    | '/tools'
    | '/topical-map'
  id:
    | '__root__'
    | '/'
    | '/briefs'
    | '/calendar'
    | '/engine'
    | '/help'
    | '/how-it-works'
    | '/keywords'
    | '/knowledge'
    | '/performance'
    | '/raffle'
    | '/reels'
    | '/scope'
    | '/settings'
    | '/strategy'
    | '/tools'
    | '/topical-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefsRoute: typeof BriefsRoute
  CalendarRoute: typeof CalendarRoute
  EngineRoute: typeof EngineRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  KeywordsRoute: typeof KeywordsRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PerformanceRoute: typeof PerformanceRoute
  RaffleRoute: typeof RaffleRoute
  ReelsRoute: typeof ReelsRoute
  ScopeRoute: typeof ScopeRoute
  SettingsRoute: typeof SettingsRoute
  StrategyRoute: typeof StrategyRoute
  ToolsRoute: typeof ToolsRoute
  TopicalMapRoute: typeof TopicalMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topical-map': {
      id: '/topical-map'
      path: '/topical-map'
      fullPath: '/topical-map'
      preLoaderRoute: typeof TopicalMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle': {
      id: '/raffle'
      path: '/raffle'
      fullPath: '/raffle'
      preLoaderRoute: typeof RaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefsRoute: BriefsRoute,
  CalendarRoute: CalendarRoute,
  EngineRoute: EngineRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  KeywordsRoute: KeywordsRoute,
  KnowledgeRoute: KnowledgeRoute,
  PerformanceRoute: PerformanceRoute,
  RaffleRoute: RaffleRoute,
  ReelsRoute: ReelsRoute,
  ScopeRoute: ScopeRoute,
  SettingsRoute: SettingsRoute,
  StrategyRoute: StrategyRoute,
  ToolsRoute: ToolsRoute,
  TopicalMapRoute: TopicalMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
