/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicalMapRouteImport } from './routes/topical-map'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SocialRouteImport } from './routes/social'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScopeRouteImport } from './routes/scope'
import { Route as ReelsRouteImport } from './routes/reels'
import { Route as RaffleRouteImport } from './routes/raffle'
import { Route as PublishQueueRouteImport } from './routes/publish-queue'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as KloudgraphRouteImport } from './routes/kloudgraph'
import { Route as KeywordsRouteImport } from './routes/keywords'
import { Route as InternalLinksRouteImport } from './routes/internal-links'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as EntityRouteImport } from './routes/entity'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as EmailRouteImport } from './routes/email'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConversionsRouteImport } from './routes/conversions'
import { Route as ContentTrackerRouteImport } from './routes/content-tracker'
import { Route as CommandRouteImport } from './routes/command'
import { Route as CitationsRouteImport } from './routes/citations'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BriefsRouteImport } from './routes/briefs'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'

const TopicalMapRoute = TopicalMapRouteImport.update({
  id: '/topical-map',
  path: '/topical-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsRoute = ReelsRouteImport.update({
  id: '/reels',
  path: '/reels',
  getParentRoute: () => rootRouteImport,
} as any)
const RaffleRoute = RaffleRouteImport.update({
  id: '/raffle',
  path: '/raffle',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishQueueRoute = PublishQueueRouteImport.update({
  id: '/publish-queue',
  path: '/publish-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const KloudgraphRoute = KloudgraphRouteImport.update({
  id: '/kloudgraph',
  path: '/kloudgraph',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordsRoute = KeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalLinksRoute = InternalLinksRouteImport.update({
  id: '/internal-links',
  path: '/internal-links',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityRoute = EntityRouteImport.update({
  id: '/entity',
  path: '/entity',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversionsRoute = ConversionsRouteImport.update({
  id: '/conversions',
  path: '/conversions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTrackerRoute = ContentTrackerRouteImport.update({
  id: '/content-tracker',
  path: '/content-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandRoute = CommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => rootRouteImport,
} as any)
const CitationsRoute = CitationsRouteImport.update({
  id: '/citations',
  path: '/citations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefsRoute = BriefsRouteImport.update({
  id: '/briefs',
  path: '/briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/citations': typeof CitationsRoute
  '/command': typeof CommandRoute
  '/content-tracker': typeof ContentTrackerRoute
  '/conversions': typeof ConversionsRoute
  '/crm': typeof CrmRoute
  '/email': typeof EmailRoute
  '/engine': typeof EngineRoute
  '/entity': typeof EntityRoute
  '/experience': typeof ExperienceRoute
  '/growth': typeof GrowthRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/internal-links': typeof InternalLinksRoute
  '/keywords': typeof KeywordsRoute
  '/kloudgraph': typeof KloudgraphRoute
  '/knowledge': typeof KnowledgeRoute
  '/learning': typeof LearningRoute
  '/performance': typeof PerformanceRoute
  '/publish-queue': typeof PublishQueueRoute
  '/raffle': typeof RaffleRoute
  '/reels': typeof ReelsRoute
  '/scope': typeof ScopeRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/strategy': typeof StrategyRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/topical-map': typeof TopicalMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/citations': typeof CitationsRoute
  '/command': typeof CommandRoute
  '/content-tracker': typeof ContentTrackerRoute
  '/conversions': typeof ConversionsRoute
  '/crm': typeof CrmRoute
  '/email': typeof EmailRoute
  '/engine': typeof EngineRoute
  '/entity': typeof EntityRoute
  '/experience': typeof ExperienceRoute
  '/growth': typeof GrowthRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/internal-links': typeof InternalLinksRoute
  '/keywords': typeof KeywordsRoute
  '/kloudgraph': typeof KloudgraphRoute
  '/knowledge': typeof KnowledgeRoute
  '/learning': typeof LearningRoute
  '/performance': typeof PerformanceRoute
  '/publish-queue': typeof PublishQueueRoute
  '/raffle': typeof RaffleRoute
  '/reels': typeof ReelsRoute
  '/scope': typeof ScopeRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/strategy': typeof StrategyRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/topical-map': typeof TopicalMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/briefs': typeof BriefsRoute
  '/calendar': typeof CalendarRoute
  '/changelog': typeof ChangelogRoute
  '/citations': typeof CitationsRoute
  '/command': typeof CommandRoute
  '/content-tracker': typeof ContentTrackerRoute
  '/conversions': typeof ConversionsRoute
  '/crm': typeof CrmRoute
  '/email': typeof EmailRoute
  '/engine': typeof EngineRoute
  '/entity': typeof EntityRoute
  '/experience': typeof ExperienceRoute
  '/growth': typeof GrowthRoute
  '/help': typeof HelpRoute
  '/how-it-works': typeof HowItWorksRoute
  '/internal-links': typeof InternalLinksRoute
  '/keywords': typeof KeywordsRoute
  '/kloudgraph': typeof KloudgraphRoute
  '/knowledge': typeof KnowledgeRoute
  '/learning': typeof LearningRoute
  '/performance': typeof PerformanceRoute
  '/publish-queue': typeof PublishQueueRoute
  '/raffle': typeof RaffleRoute
  '/reels': typeof ReelsRoute
  '/scope': typeof ScopeRoute
  '/settings': typeof SettingsRoute
  '/social': typeof SocialRoute
  '/strategy': typeof StrategyRoute
  '/studio': typeof StudioRoute
  '/tools': typeof ToolsRoute
  '/topical-map': typeof TopicalMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/briefs'
    | '/calendar'
    | '/changelog'
    | '/citations'
    | '/command'
    | '/content-tracker'
    | '/conversions'
    | '/crm'
    | '/email'
    | '/engine'
    | '/entity'
    | '/experience'
    | '/growth'
    | '/help'
    | '/how-it-works'
    | '/internal-links'
    | '/keywords'
    | '/kloudgraph'
    | '/knowledge'
    | '/learning'
    | '/performance'
    | '/publish-queue'
    | '/raffle'
    | '/reels'
    | '/scope'
    | '/settings'
    | '/social'
    | '/strategy'
    | '/studio'
    | '/tools'
    | '/topical-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/briefs'
    | '/calendar'
    | '/changelog'
    | '/citations'
    | '/command'
    | '/content-tracker'
    | '/conversions'
    | '/crm'
    | '/email'
    | '/engine'
    | '/entity'
    | '/experience'
    | '/growth'
    | '/help'
    | '/how-it-works'
    | '/internal-links'
    | '/keywords'
    | '/kloudgraph'
    | '/knowledge'
    | '/learning'
    | '/performance'
    | '/publish-queue'
    | '/raffle'
    | '/reels'
    | '/scope'
    | '/settings'
    | '/social'
    | '/strategy'
    | '/studio'
    | '/tools'
    | '/topical-map'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/briefs'
    | '/calendar'
    | '/changelog'
    | '/citations'
    | '/command'
    | '/content-tracker'
    | '/conversions'
    | '/crm'
    | '/email'
    | '/engine'
    | '/entity'
    | '/experience'
    | '/growth'
    | '/help'
    | '/how-it-works'
    | '/internal-links'
    | '/keywords'
    | '/kloudgraph'
    | '/knowledge'
    | '/learning'
    | '/performance'
    | '/publish-queue'
    | '/raffle'
    | '/reels'
    | '/scope'
    | '/settings'
    | '/social'
    | '/strategy'
    | '/studio'
    | '/tools'
    | '/topical-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  BriefsRoute: typeof BriefsRoute
  CalendarRoute: typeof CalendarRoute
  ChangelogRoute: typeof ChangelogRoute
  CitationsRoute: typeof CitationsRoute
  CommandRoute: typeof CommandRoute
  ContentTrackerRoute: typeof ContentTrackerRoute
  ConversionsRoute: typeof ConversionsRoute
  CrmRoute: typeof CrmRoute
  EmailRoute: typeof EmailRoute
  EngineRoute: typeof EngineRoute
  EntityRoute: typeof EntityRoute
  ExperienceRoute: typeof ExperienceRoute
  GrowthRoute: typeof GrowthRoute
  HelpRoute: typeof HelpRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InternalLinksRoute: typeof InternalLinksRoute
  KeywordsRoute: typeof KeywordsRoute
  KloudgraphRoute: typeof KloudgraphRoute
  KnowledgeRoute: typeof KnowledgeRoute
  LearningRoute: typeof LearningRoute
  PerformanceRoute: typeof PerformanceRoute
  PublishQueueRoute: typeof PublishQueueRoute
  RaffleRoute: typeof RaffleRoute
  ReelsRoute: typeof ReelsRoute
  ScopeRoute: typeof ScopeRoute
  SettingsRoute: typeof SettingsRoute
  SocialRoute: typeof SocialRoute
  StrategyRoute: typeof StrategyRoute
  StudioRoute: typeof StudioRoute
  ToolsRoute: typeof ToolsRoute
  TopicalMapRoute: typeof TopicalMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topical-map': {
      id: '/topical-map'
      path: '/topical-map'
      fullPath: '/topical-map'
      preLoaderRoute: typeof TopicalMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels': {
      id: '/reels'
      path: '/reels'
      fullPath: '/reels'
      preLoaderRoute: typeof ReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raffle': {
      id: '/raffle'
      path: '/raffle'
      fullPath: '/raffle'
      preLoaderRoute: typeof RaffleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish-queue': {
      id: '/publish-queue'
      path: '/publish-queue'
      fullPath: '/publish-queue'
      preLoaderRoute: typeof PublishQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kloudgraph': {
      id: '/kloudgraph'
      path: '/kloudgraph'
      fullPath: '/kloudgraph'
      preLoaderRoute: typeof KloudgraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keywords': {
      id: '/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof KeywordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-links': {
      id: '/internal-links'
      path: '/internal-links'
      fullPath: '/internal-links'
      preLoaderRoute: typeof InternalLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity': {
      id: '/entity'
      path: '/entity'
      fullPath: '/entity'
      preLoaderRoute: typeof EntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversions': {
      id: '/conversions'
      path: '/conversions'
      fullPath: '/conversions'
      preLoaderRoute: typeof ConversionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-tracker': {
      id: '/content-tracker'
      path: '/content-tracker'
      fullPath: '/content-tracker'
      preLoaderRoute: typeof ContentTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command': {
      id: '/command'
      path: '/command'
      fullPath: '/command'
      preLoaderRoute: typeof CommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citations': {
      id: '/citations'
      path: '/citations'
      fullPath: '/citations'
      preLoaderRoute: typeof CitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefs': {
      id: '/briefs'
      path: '/briefs'
      fullPath: '/briefs'
      preLoaderRoute: typeof BriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  BriefsRoute: BriefsRoute,
  CalendarRoute: CalendarRoute,
  ChangelogRoute: ChangelogRoute,
  CitationsRoute: CitationsRoute,
  CommandRoute: CommandRoute,
  ContentTrackerRoute: ContentTrackerRoute,
  ConversionsRoute: ConversionsRoute,
  CrmRoute: CrmRoute,
  EmailRoute: EmailRoute,
  EngineRoute: EngineRoute,
  EntityRoute: EntityRoute,
  ExperienceRoute: ExperienceRoute,
  GrowthRoute: GrowthRoute,
  HelpRoute: HelpRoute,
  HowItWorksRoute: HowItWorksRoute,
  InternalLinksRoute: InternalLinksRoute,
  KeywordsRoute: KeywordsRoute,
  KloudgraphRoute: KloudgraphRoute,
  KnowledgeRoute: KnowledgeRoute,
  LearningRoute: LearningRoute,
  PerformanceRoute: PerformanceRoute,
  PublishQueueRoute: PublishQueueRoute,
  RaffleRoute: RaffleRoute,
  ReelsRoute: ReelsRoute,
  ScopeRoute: ScopeRoute,
  SettingsRoute: SettingsRoute,
  SocialRoute: SocialRoute,
  StrategyRoute: StrategyRoute,
  StudioRoute: StudioRoute,
  ToolsRoute: ToolsRoute,
  TopicalMapRoute: TopicalMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
